"""fixed migration issue

Revision ID: 3bf2cd504615
Revises: 666ce7e3c0ea
Create Date: 2025-12-28 12:39:09.166641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf2cd504615'
down_revision: Union[str, Sequence[str], None] = '666ce7e3c0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timers', 'conversation_id',
               existing_type=sa.VARCHAR(length=100),
               comment='External conversation identifier',
               existing_nullable=True)
    op.alter_column('timers', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Description of what the timer is for',
               existing_nullable=False)
    op.alter_column('timers', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment='Total duration in seconds',
               existing_nullable=False)
    op.alter_column('timers', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='When the timer will end',
               existing_nullable=False)
    op.alter_column('timers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Current status of the timer',
               existing_nullable=False)
    op.alter_column('timers', 'paused_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when the timer was paused',
               existing_nullable=True)
    op.alter_column('timers', 'remaining_seconds',
               existing_type=sa.INTEGER(),
               comment='Seconds remaining when paused',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timers', 'remaining_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Seconds remaining when paused',
               existing_nullable=True)
    op.alter_column('timers', 'paused_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when the timer was paused',
               existing_nullable=True)
    op.alter_column('timers', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Current status of the timer',
               existing_nullable=False)
    op.alter_column('timers', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='When the timer will end',
               existing_nullable=False)
    op.alter_column('timers', 'duration_seconds',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total duration in seconds',
               existing_nullable=False)
    op.alter_column('timers', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Description of what the timer is for',
               existing_nullable=False)
    op.alter_column('timers', 'conversation_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='External conversation identifier',
               existing_nullable=True)
    # ### end Alembic commands ###
